LISST_TO_MEDIAPOSE={ 
                'root': [],
                'lhipjoint': [23],
                'lfemur': [25],
                'ltibia':[27],
                'lfoot':[27, 31],
                'ltoes':[31],
                'rhipjoint':[24],
                'rfemur':[26],
                'rtibia':[28],
                'rfoot':[28, 32],
                'rtoes':[32],
                'lowerback': [],
                'upperback':[],
                'thorax':[],
                'lowerneck':[11, 12],
                'upperneck':[],
                'head':[7, 8],
                'lclavicle':[11],
                'lhumerus':[13],
                'lradius':[15],
                'lwrist':[15],
                'lhand':[17, 19],
                'lfingers':[],
                'lthumb':[21],
                'rclavicle':[12],
                'rhumerus':[14],
                'rradius':[16],
                'rwrist':[16],
                'rhand':[18,20],
                'rfingers':[],
                'rthumb':[22],            
                'nose': [0],
                'lheel':[29],
                'rheel': [30]
        }

